version: '3.8'

services:
  shblog:
    container_name: shblog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
